version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/bin/docker
      - ./jenkins_home:/var/jenkins_home

  registry:
    image: registry
    container_name: registry
    restart: always
    ports:
      - 5000:5000
